import type { ResumeData } from '../../scripts/resume/data.ts';
import { metadata } from '../shared/head.ts';
import { renderProfile } from './sections/profile.ts';
import { renderHistory } from './sections/history.ts';
import { renderProjects } from './sections/projects.ts';

export function renderResume(data: ResumeData): string {
  const { site, profile, history, sections, projects } = data;
  return `<!doctype html>
<!-- Generated by npm run build:resume. Edit data/ and ui/resume/ instead. -->
<html lang="ko">
<head>
${metadata(site)}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/theme/resume/resume.css">
</head>
<body>

<header class="toolbar">
  <a href="/">← 포트폴리오</a>
  <a href="/resume/jaewon-lee-resume.pdf" download>PDF 내려받기</a>
  <button type="button" onclick="window.print()">인쇄</button>
</header>

<main class="sheet">
${renderProfile(profile)}

${renderHistory(sections.historyTitle, history)}

${renderProjects(sections.projectsTitle, sections.groups, projects)}
</main>

</body>
</html>
`;
}
